name: "demo"
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflow/**'
      - '__test__/**'
      - 'src/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: lint and test
        run: npm i
             npm run lint
             npm run test:remote
